// Copyright (c) Tim Gordon.
// This file is licensed to you under the Apache Licence, Version 2.0. See the LICENSE file.

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace NXOld.NXComponents;

/// <summary>
/// Represents a transition to a new <see cref="State"/> for the specified <see cref="AsciiCharSet"/>.
/// </summary>
#if DEBUG
[DebuggerDisplay("{DebuggerDisplay,nq}")]
#endif
public readonly struct Transition : IEquatable<Transition>
{
	#region Public data
	/// <summary>
	/// Represents the transition from the given state for the specified set of characters to the next state.
	/// <para>For the end of text transition, simply use <see langword="default"/>.</para>
	/// </summary>
	public AsciiCharSet CharSet { get; }
	/// <summary>
	/// The <see cref="State"/> to which this transition leads.
	/// </summary>
	public State NextState { get; }
	#endregion
	#region Public ctor/dctor
	/// <summary>
	/// Initialises a new <see cref="Transition"/>.
	/// </summary>
	/// <param name="charSet">
	/// The ASCII characters required to take this transition to <paramref name="nextState"/>.
	/// <para>
	/// Empty represents the end of text, in which case <paramref name="nextState"/> must be null.
	/// </para>
	/// <para>
	/// Prefer <see langword="default"/> if you know you're dealing with the end of text transition.
	/// </para>
	/// </param>
	/// <param name="nextState">
	/// The <see cref="State"/> to which this transition leads.
	/// <para>
	/// If this is null then <paramref name="charSet"/> must be empty.
	/// </para>
	/// <para>
	/// Prefer <see langword="default"/> if you know you're dealing with the end of text transition.
	/// </para>
	/// </param>
	public Transition(AsciiCharSet charSet, State nextState)
	{
		if (charSet.IsEmpty != nextState.IsNull) { Throw(); }

		this.CharSet = charSet;
		this.NextState = nextState;
	}
	/// <summary>
	/// Deconstructs a <see cref="Transition"/>.
	/// </summary>
	/// <param name="charSet">The ASCII characters required to take this transition to <paramref name="nextState"/>.</param>
	/// <param name="nextState">The <see cref="State"/> to which this transition leads.</param>
	public void Deconstruct(out AsciiCharSet charSet, out State nextState)
	{
		charSet = this.CharSet;
		nextState = this.NextState;
	}
	#endregion
	#region Public methods
	/// <summary>
	/// The number of character encoding combinations generated by this transition.
	/// </summary>
	public ulong CharacterCombinationCount => Math.Max(1, ((ulong)this.CharSet.Count) * this.NextState.CharacterCombinationCount);
	/// <inheritdoc/>
	public bool Equals(Transition other) => this.CharSet == other.CharSet && this.NextState == other.NextState;
	/// <inheritdoc/>
	public override bool Equals([NotNullWhen(true)] object? obj)
		=> obj is Transition other && this.Equals(other);
	/// <inheritdoc/>
	public override int GetHashCode() => HashCode.Combine(this.CharSet, this.NextState);
	#endregion
	#region Internal properties and methods
#if DEBUG
	internal string DebuggerDisplay => $"{this.CharSet} → {this.NextState.DebuggerDisplay}";
#endif
	#endregion
	#region Private static properties and methods
	[DoesNotReturn]
	static void Throw() => throw new ArgumentException("charSet can be empty if and only if nextState is null.");
	#endregion
}