// Copyright (c) Tim Gordon.
// This file is licensed to you under the Apache Licence, Version 2.0. See the LICENSE file.

namespace LogMu.Generator;

/// <summary>
/// The attribute the generator looks for, which it adds to the user's own compilation rather
/// than the naxp library exposing it.
/// </summary>
/// <remarks>
/// <para>
/// Generated recognisers depend on nothing at run time, and injecting the attribute keeps that
/// true of the declaration as well: a project can reference naxp for the generator alone. It
/// also leaves <c>Naxp</c> as the library's only public type.
/// </para>
/// <para>
/// <c>NaxpAttribute</c> shares its namespace, and all but its suffix, with the library's public
/// <c>Naxp</c> class. That is not the ambiguity it looks like: C# resolves <c>[Naxp]</c> against
/// both names but considers only attribute classes, and <c>Naxp</c> is not one. A file can carry
/// <c>[Naxp(...)]</c> and call <c>Naxp.Parse(...)</c> under one using directive.
/// </para>
/// <para>
/// Nothing here is newer than C# 6, because it is compiled with whatever language version the
/// user's project sets.
/// </para>
/// </remarks>
static class AttributeSource
{
	/// <summary>The metadata name the generator matches on.</summary>
	public const string AttributeMetadataName = "LogMu.NaxpAttribute";

	/// <summary>The file the generator adds at post-initialisation.</summary>
	public const string HintName = "NaxpAttribute.g.cs";

	const string Template = """
		// <auto-generated/>
		// Added by the naxp source generator, version {version}. Do not edit.

		namespace LogMu
		{
			/// <summary>
			/// Generates recogniser and codec code for a naxp as members of the type it is applied to.
			/// </summary>
			/// <remarks>
			/// The type must be partial, must not be generic, and must be nested only in partial types.
			/// Several naxps may share a type as long as each has its own <see cref="Prefix"/>.
			/// This attribute is read at compile time only and is not written into the assembly.
			/// </remarks>
			[global::System.AttributeUsage(
				global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct,
				AllowMultiple = true,
				Inherited = false)]
			[global::System.CodeDom.Compiler.GeneratedCode("naxp", "{version}")]
			[global::System.Diagnostics.Conditional("NAXP_KEEP_ATTRIBUTE_IN_METADATA")]
			internal sealed class NaxpAttribute : global::System.Attribute
			{
				/// <summary>Applies a naxp to this type.</summary>
				/// <param name="naxp">The naxp itself, such as <c>@"\A\9\X \s! \9\A\A"</c>.</param>
				/// <param name="valueType">
				/// The integer type the generated code encodes to, one of <c>typeof(sbyte)</c>,
				/// <c>typeof(byte)</c>, <c>typeof(short)</c>, <c>typeof(ushort)</c>,
				/// <c>typeof(int)</c>, <c>typeof(uint)</c>, <c>typeof(long)</c> and
				/// <c>typeof(ulong)</c>. It is stated rather than inferred so that a naxp which
				/// outgrows it is refused, instead of quietly widening what the generated members
				/// return.
				/// </param>
				public NaxpAttribute(string naxp, global::System.Type valueType)
				{
					this.Naxp = naxp;
					this.ValueType = valueType;
				}

				/// <summary>The naxp.</summary>
				public string Naxp { get; }

				/// <summary>The integer type the generated code encodes to.</summary>
				public global::System.Type ValueType { get; }

				/// <summary>
				/// The prefix every generated member name starts with, such as <c>Postcode</c> for
				/// <c>PostcodeAccepts</c>. Blank, the default, gives bare names such as
				/// <c>Accepts</c>, which suits a type holding one naxp. A type holding several
				/// needs a different prefix for each.
				/// </summary>
				public string Prefix { get; set; } = "";
			}
		}

		""";

	/// <summary>The attribute source, carrying the generator's version.</summary>
	public static string Text { get; } = Template.Replace("{version}", Emitter.PackageVersion());
}
