# Copyright (c) Tim Gordon.
# This file is licensed to you under the Apache Licence, Version 2.0. See the LICENSE file.

"""The authored half of the test data: which naxps, what each is here to show.

Nothing derived lives here. Every count, every encoded value and every canonical form is
worked out by `generate.py` from the naxp alone. What this file holds is the choice of naxp,
the note that says why it is worth a case, the text that must be invalid for it, and -- where
the accepted language is too large to list -- which strings to sample.

A case with no `samples` is complete: `generate.py` lists every string it accepts, so the
encoded values are also a bijection onto 1..maxEncodedValue.
"""

CASES = [
    {
        "naxp": "A",
        "note": "the simplest naxp",
        "invalid": ["B", "", "AA"],
    },
    {
        "naxp": "A?",
        "note": "an optional element; the choice is encoded",
        "invalid": ["B", "AA"],
    },
    {
        "naxp": "()",
        "note": "the empty string is a naxp in its own right",
        "invalid": ["A"],
    },
    {
        "naxp": "A|()",
        "note": "an empty alternative denotes the same strings as A?",
        "invalid": ["B"],
    },
    {
        "naxp": "AB|B",
        "note": "class [A] precedes class [B], so AB takes value 1",
        "invalid": ["A", ""],
    },
    {
        "naxp": "A(B|C)",
        "note": "grouped alternation",
        "invalid": ["A", "AD"],
    },
    {
        "naxp": "AB|AC",
        "note": "the same language written differently; values must match",
        "invalid": ["A"],
    },
    {
        "naxp": "[ABC]C",
        "note": "a three character set",
        "invalid": ["AB", "DC"],
    },
    {
        "naxp": "[AB]C|[BC]C",
        "note": "minterms refine the classes; merging recombines them",
        "invalid": ["DC"],
    },
    {
        "naxp": "A?A?",
        "note": "overlapping options",
        "invalid": ["AAA", "B"],
    },
    {
        "naxp": "(AA)?|A",
        "note": "the same language as A?A?",
        "invalid": ["AAA"],
    },
    {
        "naxp": "A|A",
        "note": "a duplicated alternative changes nothing",
        "invalid": ["B"],
    },
    {
        "naxp": "A|B|C",
        "note": "three alternatives",
        "invalid": ["D", "AB"],
    },
    {
        "naxp": "(A|B)(C|D)",
        "note": "a product of two choices",
        "invalid": ["AB", "A"],
    },
    {
        "naxp": "\\s",
        "note": "a space is written as an escape",
        "invalid": ["", "A"],
    },
    {
        "naxp": "[\\9A-F]",
        "note": "a block escape combined with a range",
        "invalid": ["G", "a"],
    },
    {
        "naxp": "\\X\\x",
        "note": "the two mixed block escapes side by side: a digit or an upper case letter, then a digit or a lower case letter, 36 by 36",
        "invalid": ["aA", "AA", "aa", "A", "A1A"],
    },
    {
        "naxp": "\\!\\#\\(\\)\\,\\-\\?\\[\\\\\\]\\{\\|\\}\\*\\+\\.\\^\\$",
        "note": "every reserved character escaped, the five regex metacharacters included",
        "invalid": ["!"],
    },
    {
        "naxp": "#[0-9]",
        "note": "a decimal range equal to a plain set",
        "invalid": ["10", "a"],
    },
    {
        "naxp": "#[0-10]",
        "note": "the spec's worked value; 1 sorts above 9",
        "invalid": ["11", "007", ""],
    },
    {
        "naxp": "#[00-10]",
        "note": "padding the lower bound restores numeric order",
        "invalid": ["0", "11"],
    },
    {
        "naxp": "#[0-105]",
        "note": "three widths",
        "invalid": ["106", "00"],
    },
    {
        "naxp": "#[00-105]",
        "note": "a minimum width of two",
        "invalid": ["7", "106"],
    },
    {
        "naxp": "#[000-105]",
        "note": "a fixed width of three; the control for the marked cases below",
        "invalid": ["7", "07", "106"],
    },
    {
        "naxp": "#[0!0!0-105]",
        "note": "every padding position marked to keep its zero; one to three digits in, three out, and the values of #[000-105]",
        "invalid": ["0007", "0105", "106"],
    },
    {
        "naxp": "#[0?0?0-105]",
        "note": "every padding position marked to drop its zero; the values of #[0-105], so the order is the one that puts 1 above 9",
        "invalid": ["0007", "106"],
    },
    {
        "naxp": "#[0?0!0-105]",
        "note": "the marks mixed, read outside in: a minimum canonical width of two, and the values of #[00-105]",
        "invalid": ["0007", "106"],
    },
    {
        "naxp": "#[0!0?0-105]",
        "note": "the marks interleaved the other way, giving canonical widths of two, three and three",
        "invalid": ["0007", "106"],
    },
    {
        "naxp": "#[00!0-999]",
        "note": "an unmarked padding position stays mandatory, so this admits two or three digits and never one",
        "invalid": ["7", "42", "0042"],
    },
    {
        "naxp": "#[0!0-09]\\A",
        "note": "a marked range needs a neighbour of fixed width; the single letter fixes where the range stops, so W3 holds",
        "invalid": ["7", "07", "0071", "A"],
    },
    {
        "naxp": "A{2,4}",
        "note": "a bounded interval",
        "invalid": ["A", "AAAAA"],
    },
    {
        "naxp": "AAA?A?",
        "note": "the same language as A{2,4}",
        "invalid": ["A"],
    },
    {
        "naxp": "A{0,3}",
        "note": "up to three",
        "invalid": ["AAAA"],
    },
    {
        "naxp": "\\9{3}",
        "note": "three digit positions, numeric order preserved",
        "samples": [
            "000",
            "001",
            "002",
            "015",
            "041",
            "046",
            "054",
            "063",
            "065",
            "068",
            "074",
            "088",
            "103",
            "115",
            "128",
            "155",
            "159",
            "174",
            "178",
            "181",
            "183",
            "184",
            "186",
            "188",
            "192",
            "207",
            "236",
            "246",
            "262",
            "272",
            "274",
            "289",
            "300",
            "303",
            "304",
            "313",
            "332",
            "338",
            "339",
            "348",
            "352",
            "353",
            "358",
            "366",
            "367",
            "368",
            "373",
            "376",
            "377",
            "380",
            "383",
            "386",
            "417",
            "423",
            "426",
            "428",
            "443",
            "445",
            "455",
            "463",
            "472",
            "473",
            "475",
            "477",
            "478",
            "483",
            "488",
            "493",
            "499",
            "504",
            "505",
            "512",
            "534",
            "537",
            "544",
            "556",
            "561",
            "568",
            "592",
            "597",
            "602",
            "608",
            "612",
            "613",
            "621",
            "626",
            "632",
            "643",
            "648",
            "653",
            "686",
            "694",
            "702",
            "710",
            "713",
            "719",
            "723",
            "725",
            "734",
            "741",
            "748",
            "752",
            "756",
            "774",
            "776",
            "804",
            "805",
            "815",
            "830",
            "840",
            "852",
            "854",
            "857",
            "877",
            "902",
            "909",
            "915",
            "917",
            "921",
            "922",
            "927",
            "938",
            "943",
            "965",
            "980",
            "990",
            "998",
            "999",
            "003",
            "004",
            "005",
            "006",
            "007",
            "008",
            "009",
            "010",
            "011",
            "012",
            "013",
            "014",
            "016",
            "017",
            "018",
            "019",
            "020",
            "021",
            "022",
            "023",
            "024",
            "025",
            "026",
            "027",
            "028",
            "029",
            "030",
            "031",
            "032",
            "033",
            "034",
            "035",
            "036",
            "037",
            "038",
            "039",
            "040",
            "042",
            "043",
            "044",
            "045",
            "047",
            "048",
            "049",
            "050",
            "051",
            "052",
            "053",
            "055",
            "056",
            "057",
            "058",
            "059",
            "060",
            "061",
            "062",
            "064",
            "066",
            "067",
            "069",
            "070",
            "071",
            "072",
            "073",
            "075",
            "076",
            "077",
            "078",
            "079",
            "080",
            "081",
            "082",
            "083",
            "084",
            "085",
            "086",
            "087",
            "089",
            "090",
            "091",
            "092",
            "093",
            "094",
            "095",
            "096",
            "097",
            "098",
            "099",
            "100",
            "101",
            "102",
            "104",
            "105",
            "106",
            "107",
            "108",
            "109",
            "110",
            "111",
            "112",
            "113",
            "114",
            "116",
            "117",
            "118",
            "119",
            "120",
            "121",
            "122",
            "123",
            "124",
            "125",
            "126",
            "127",
            "129",
            "130",
            "131",
            "132",
            "133",
            "134",
            "135",
            "136",
            "137",
            "138",
            "139",
            "140",
            "141",
            "142",
            "143",
            "144",
            "145",
            "146",
            "147",
            "148",
            "149",
            "150",
            "151",
            "152",
            "153",
            "154",
            "156",
            "157",
            "158",
            "160",
            "161",
            "162",
            "163",
            "164",
            "165",
            "166",
            "167",
            "168",
            "169",
            "170",
            "171",
            "172",
            "173",
            "175",
            "176",
            "177",
            "179",
            "180",
            "182",
            "185",
            "187",
            "189",
            "190",
            "191",
            "193",
            "194",
            "195",
            "196",
            "197",
            "198",
            "199",
            "200",
            "201",
            "202",
            "203",
            "204",
            "205",
            "206",
            "208",
            "209",
            "210",
            "211",
            "212",
            "213",
            "214",
            "215",
            "216",
            "217",
            "218",
            "219",
            "220",
            "221",
            "222",
            "223",
            "224",
            "225",
            "226",
            "227",
            "228",
            "229",
            "230",
            "231",
            "232",
            "233",
            "234",
            "235",
            "237",
            "238",
            "239",
            "240",
            "241",
            "242",
            "243",
            "244",
            "245",
            "247",
            "248",
            "249",
            "250",
            "251",
            "252",
            "253",
            "254",
            "255",
            "256",
            "257",
            "258",
            "259",
            "260",
            "261",
            "263",
            "264",
            "265",
            "266",
            "267",
            "268",
            "269",
            "270",
            "271",
            "273",
            "275",
            "276",
            "277",
            "278",
            "279",
            "280",
            "281",
            "282",
            "283",
            "284",
            "285",
            "286",
            "287",
            "288",
            "290",
            "291",
            "292",
            "293",
            "294",
            "295",
            "296",
            "297",
            "298",
            "299",
            "301",
            "302",
            "305",
            "306",
            "307",
            "308",
            "309",
            "310",
            "311",
            "312",
            "314",
            "315",
            "316",
            "317",
            "318",
            "319",
            "320",
            "321",
            "322",
            "323",
            "324",
            "325",
            "326",
            "327",
            "328",
            "329",
            "330",
            "331",
            "333",
            "334",
            "335",
            "336",
            "337",
            "340",
            "341",
            "342",
            "343",
            "344",
            "345",
            "346",
            "347",
            "349",
            "350",
            "351",
            "354",
            "355",
            "356",
            "357",
            "359",
            "360",
            "361",
            "362",
            "363",
            "364",
            "365",
            "369",
            "370",
            "371",
            "372",
            "374",
            "375",
            "378",
            "379",
            "381",
            "382",
            "384",
            "385",
            "387",
            "388",
            "389",
            "390",
            "391",
            "392",
            "393",
            "394",
            "395",
            "396",
            "397",
            "398",
            "399",
            "400",
            "401",
            "402",
            "403",
            "404",
            "405",
            "406",
            "407",
            "408",
            "409",
            "410",
            "411",
            "412",
            "413",
            "414",
            "415",
            "416",
            "418",
            "419",
            "420",
            "421",
            "422",
            "424",
            "425",
            "427",
            "429",
            "430",
            "431",
            "432",
            "433",
            "434",
            "435",
            "436",
            "437",
            "438",
            "439",
            "440",
            "441",
            "442",
            "444",
            "446",
            "447",
            "448",
            "449",
            "450",
            "451",
            "452",
            "453",
            "454",
            "456",
            "457",
            "458",
            "459",
            "460",
            "461",
            "462",
            "464",
            "465",
            "466",
            "467",
            "468",
            "469",
            "470",
            "471",
            "474",
            "476",
            "479",
            "480",
            "481",
            "482",
            "484",
            "485",
            "486",
            "487",
            "489",
            "490",
            "491",
            "492",
            "494",
            "495",
            "496",
            "497",
            "498",
            "500",
            "501",
            "502",
            "503",
            "506",
            "507",
            "508",
            "509",
            "510",
            "511",
            "513",
            "514",
            "515",
            "516",
            "517",
            "518",
            "519",
            "520",
            "521",
            "522",
            "523",
            "524",
            "525",
            "526",
            "527",
            "528",
            "529",
            "530",
            "531",
            "532",
            "533",
            "535",
            "536",
            "538",
            "539",
            "540",
            "541",
            "542",
            "543",
            "545",
            "546",
            "547",
            "548",
            "549",
            "550",
            "551",
            "552",
            "553",
            "554",
            "555",
            "557",
            "558",
            "559",
            "560",
            "562",
            "563",
            "564",
            "565",
            "566",
            "567",
            "569",
            "570",
            "571",
            "572",
            "573",
            "574",
            "575",
            "576",
            "577",
            "578",
            "579",
            "580",
            "581",
            "582",
            "583",
            "584",
            "585",
            "586",
            "587",
            "588",
            "589",
            "590",
            "591",
            "593",
            "594",
            "595",
            "596",
            "598",
            "599",
            "600",
            "601",
            "603",
            "604",
            "605",
            "606",
            "607",
            "609",
            "610",
            "611",
            "614",
            "615",
            "616",
            "617",
            "618",
            "619",
            "620",
            "622",
            "623",
            "624",
            "625",
            "627",
            "628",
            "629",
            "630",
            "631",
            "633",
            "634",
            "635",
            "636",
            "637",
            "638",
            "639",
            "640",
            "641",
            "642",
            "644",
            "645",
            "646",
            "647",
            "649",
            "650",
            "651",
            "652",
            "654",
            "655",
            "656",
            "657",
            "658",
            "659",
            "660",
            "661",
            "662",
            "663",
            "664",
            "665",
            "666",
            "667",
            "668",
            "669",
            "670",
            "671",
            "672",
            "673",
            "674",
            "675",
            "676",
            "677",
            "678",
            "679",
            "680",
            "681",
            "682",
            "683",
            "684",
            "685",
            "687",
            "688",
            "689",
            "690",
            "691",
            "692",
            "693",
            "695",
            "696",
            "697",
            "698",
            "699",
            "700",
            "701",
            "703",
            "704",
            "705",
            "706",
            "707",
            "708",
            "709",
            "711",
            "712",
            "714",
            "715",
            "716",
            "717",
            "718",
            "720",
            "721",
            "722",
            "724",
            "726",
            "727",
            "728",
            "729",
            "730",
            "731",
            "732",
            "733",
            "735",
            "736",
            "737",
            "738",
            "739",
            "740",
            "742",
            "743",
            "744",
            "745",
            "746",
            "747",
            "749",
            "750",
            "751",
            "753",
            "754",
            "755",
            "757",
            "758",
            "759",
            "760",
            "761",
            "762",
            "763",
            "764",
            "765",
            "766",
            "767",
            "768",
            "769",
            "770",
            "771",
            "772",
            "773",
            "775",
            "777",
            "778",
            "779",
            "780",
            "781",
            "782",
            "783",
            "784",
            "785",
            "786",
            "787",
            "788",
            "789",
            "790",
            "791",
            "792",
            "793",
            "794",
            "795",
            "796",
            "797",
            "798",
            "799",
            "800",
            "801",
            "802",
            "803",
            "806",
            "807",
            "808",
            "809",
            "810",
            "811",
            "812",
            "813",
            "814",
            "816",
            "817",
            "818",
            "819",
            "820",
            "821",
            "822",
            "823",
            "824",
            "825",
            "826",
            "827",
            "828",
            "829",
            "831",
            "832",
            "833",
            "834",
            "835",
            "836",
            "837",
            "838",
            "839",
            "841",
            "842",
            "843",
            "844",
            "845",
            "846",
            "847",
            "848",
            "849",
            "850",
            "851",
            "853",
            "855",
            "856",
            "858",
            "859",
            "860",
            "861",
            "862",
            "863",
            "864",
            "865",
            "866",
            "867",
            "868",
            "869",
            "870",
            "871",
            "872",
            "873",
            "874",
            "875",
            "876",
            "878",
            "879",
            "880",
            "881",
            "882",
            "883",
            "884",
            "885",
            "886",
            "887",
            "888",
            "889",
            "890",
            "891",
            "892",
            "893",
            "894",
            "895",
            "896",
            "897",
            "898",
            "899",
            "900",
            "901",
            "903",
            "904",
            "905",
            "906",
            "907",
            "908",
            "910",
            "911",
            "912",
            "913",
            "914",
            "916",
            "918",
            "919",
            "920",
            "923",
            "924",
            "925",
            "926",
            "928",
            "929",
            "930",
            "931",
            "932",
            "933",
            "934",
            "935",
            "936",
            "937",
            "939",
            "940",
            "941",
            "942",
            "944",
            "945",
            "946",
            "947",
            "948",
            "949",
            "950",
            "951",
            "952",
            "953",
            "954",
            "955",
            "956",
            "957",
            "958",
            "959",
            "960",
            "961",
            "962",
            "963",
            "964",
            "966",
            "967",
            "968",
            "969",
            "970",
            "971",
            "972",
            "973",
            "974",
            "975",
            "976",
            "977",
            "978",
            "979",
            "981",
            "982",
            "983",
            "984",
            "985",
            "986",
            "987",
            "988",
            "989",
            "991",
            "992",
            "993",
            "994",
            "995",
            "996",
            "997",
        ],
        "invalid": ["12", "1234"],
    },
    {
        "naxp": "[0-5]\\9",
        "note": "independent digit sets of fixed width",
        "invalid": ["60", "6"],
    },
    {
        "naxp": "(A|a)!A",
        "note": "case folding: both cases encode alike and print the capital",
        "invalid": ["B"],
    },
    {
        "naxp": "\\A!?",
        "note": "a capital or nothing, discarded and printed as nothing",
        "invalid": ["a"],
    },
    {
        "naxp": "\\s!!X",
        "note": "an optional space, reproduced on reconstitution",
        "invalid": ["  X", "x"],
    },
    {
        "naxp": "[\\s\\-]?!\\-",
        "note": "space, hyphen or nothing; prints a hyphen",
        "invalid": ["A"],
    },
    {
        "naxp": "[\\s\\-]!?",
        "note": "the same values as the previous case, different text",
        "invalid": ["A"],
    },
    {
        "naxp": "(A|b)!bX|BY",
        "note": "the counterexample that pins reading (a)",
        "invalid": ["AY", "bY"],
    },
    {
        "naxp": "(A|b)!AX|BY",
        "note": "differs from the previous case only in the rendering",
        "invalid": ["AY"],
    },
    {
        "naxp": "(a|A)!AX|AY",
        "note": "one fibre leaves the start state by two transitions",
        "invalid": ["aY"],
    },
    {
        "naxp": "\\CA",
        "note": "a fold over one letter, which is `(A|a)!A` written short",
        "invalid": ["B", "", "AA"],
    },
    {
        "naxp": "\\cA",
        "note": "the same fold with lower case canonical",
        "invalid": ["B", "", "AA"],
    },
    {
        "naxp": "\\C[A-F]",
        "note": "a fold over a set; the canonical language is the set of capitals",
        "invalid": ["G", "g", "", "AB"],
    },
    {
        "naxp": "\\c[A-F]",
        "note": "the same set folded the other way; the same values, printed in lower case",
        "invalid": ["G", "g", "", "AB"],
    },
    {
        "naxp": "\\C[a-f]",
        "note": "the case a set is written in does not decide the canonical case, the operator does",
        "invalid": ["G", "g", "", "AB"],
    },
    {
        "naxp": "\\C[\\9A-F]",
        "note": "characters with no case pass through a fold untouched",
        "invalid": ["G", "g", "", "0A"],
    },
    {
        "naxp": "\\C\\9",
        "note": "a fold over characters with no case is legal and does nothing",
        "invalid": ["A", "", "00"],
    },
    {
        "naxp": "\\CAB",
        "note": "a case fold runs to the end of the enclosing group, so both letters fold",
        "invalid": ["A", "", "ABC"],
    },
    {
        "naxp": "(\\CA)B",
        "note": "grouping the case fold is how it is stopped short, so only the A folds",
        "invalid": ["Ab", "ab", "A", ""],
    },
    {
        "naxp": "\\CA|b",
        "note": "a case fold crosses a `|`, so this is `\\C(A|b)` and prints `B` for `b`",
        "invalid": ["ab", "AB", ""],
    },
    {
        "naxp": "\\Ca\\cb",
        "note": "a later case fold sits inside the earlier one's extent and the outer governs, so this prints `AB`",
        "invalid": ["a", "b", ""],
    },
    {
        "naxp": "\\CA!A",
        "note": "a fold binds looser than `!`, so this is `\\C(A!A)` and not `(\\CA)!A`",
        "invalid": ["B", "", "AA"],
    },
    {
        "naxp": "\\CA?",
        "note": "a fold binds looser than a quantifier and reaches inside it",
        "invalid": ["B", "AA"],
    },
    {
        "naxp": "\\CA{2}",
        "note": "the same, over an interval",
        "invalid": ["A", "", "AAA"],
    },
    {
        "naxp": "\\CA!!",
        "note": "`!!` under a fold: the subject widens and the rendering keeps its canonical case",
        "invalid": ["B", "AA"],
    },
    {
        "naxp": "\\C((AB)!!)",
        "note": "the same over a group, so the pair is optional and reproduced as capitals",
        "invalid": ["A", "ABAB"],
    },
    {
        "naxp": "\\C(AB\\cC)",
        "note": "where two folds meet the outer governs, so this prints `ABC`",
        "invalid": ["AB", "", "ABCD"],
    },
    {
        "naxp": "\\c\\CA",
        "note": "a fold written directly on a fold is the outer one and never an error, so this is `\\cA`",
        "invalid": ["B", "", "aa"],
    },
    {
        "naxp": "(\\C\\9)!5",
        "note": "every rule reads the expansion, and a fold over characters with no case expands to nothing, so W2 has nothing to refuse here",
        "invalid": ["A", "", "55"],
    },
    {
        "naxp": "[a-c]{2}",
        "note": "the comparator for the two folds below",
        "invalid": ["d", "a", "", "aaa"],
    },
    {
        "naxp": "\\C([a-c]{2})",
        "note": "wrapping a lower case naxp in `\\C` keeps every encoded value and its order, and decodes all of them into the other case",
        "invalid": ["d", "D", "a", "", "aaa"],
    },
    {
        "naxp": "\\c([a-c]{2})",
        "note": "the fold that matches the case the naxp already prints, which preserves the encoding whole",
        "invalid": ["d", "D", "a", "", "aaa"],
    },
    {
        "naxp": "\\A \\A? \\9 \\X? \\s!! \\9 \\A \\A",
        "note": "UK postcodes; the separating space is optional on input",
        "samples": [
            "M1 1AA",
            "M11AA",
            "CR2 6XH",
            "CR26XH",
            "DN55 1PT",
            "DN551PT",
            "W1A 1AA",
            "W1A1AA",
            "EC1A 1BB",
            "EC1A1BB",
            "A0 0AA",
            "A0 0AB",
            "ZZ9Z 9ZY",
            "ZZ9Z 9ZZ",
        ],
        "invalid": ["1M1 1AA", "M1  1AA", "M1 1A", ""],
    },
    {
        "naxp": "\\C(\\A \\A? \\9 \\X? \\s!! \\9 \\A \\A)",
        "note": "the postcode above wrapped in a fold; every encoded value is where it was and more spellings reach it",
        "samples": [
            "M1 1AA",
            "M11AA",
            "CR2 6XH",
            "CR26XH",
            "DN55 1PT",
            "DN551PT",
            "W1A 1AA",
            "W1A1AA",
            "EC1A 1BB",
            "EC1A1BB",
            "A0 0AA",
            "A0 0AB",
            "ZZ9Z 9ZY",
            "ZZ9Z 9ZZ",
            "ec1a 1bb",
            "Ec1A 1bB",
            "ec1a1bb",
            "m1 1aa",
            "dn55 1pt",
            "zz9z 9zz",
        ],
        "invalid": ["1M1 1AA", "M1  1AA", "m1 1a", ""],
    },
    {
        "naxp": "\\9{19}",
        "note": "nineteen digit positions; W5 admits the 10^19 values and refuses \\9{20}. The samples cross 2^53 and 2^63, so this is the case that needs unsigned arithmetic.",
        "samples": [
            "0000000000000000000",
            "0000000000000000001",
            "0009007199254740990",
            "0009007199254740991",
            "1234567890123456789",
            "9223372036854775806",
            "9223372036854775807",
            "9999999999999999998",
            "9999999999999999999",
        ],
        "invalid": ["", "999999999999999999", "00000000000000000000", "000000000000000000A"],
    },
    {
        "naxp": "\\A{7}\\9{9}",
        "note": "seven letters then nine digits, a mixed radix count above 2^53; the boundary itself is sampled.",
        "samples": [
            "AAAAAAA000000000",
            "AAAAAAA000000001",
            "AATSMGT254740990",
            "AATSMGT254740991",
            "NAXPXYZ123456789",
            "ZZZZZZZ999999998",
            "ZZZZZZZ999999999",
        ],
        "invalid": ["", "AAAAAAA00000000", "AAAAAA0000000000", "aaaaaaa000000000"],
    },
    {
        "naxp": "(A{50}){39}A{49}",
        "note": "1999 positions, so 2000 states, which is exactly what W6 allows",
        "invalid": ["", "A", "AA"],
    },
]

INVALID_NAXPS = [
    {"naxp": "A!", "rule": "syntax",
     "note": "there is deliberately no bare `x!`"},
    {"naxp": "A??", "rule": "syntax",
     "note": "an atom may take only one quantifier"},
    {"naxp": "A{2}?", "rule": "syntax",
     "note": "an atom may take only one quantifier"},
    {"naxp": "A?{2}", "rule": "syntax",
     "note": "an atom may take only one quantifier"},
    {"naxp": "A?!!", "rule": "syntax",
     "note": "`!!` carries its own `?`"},
    {"naxp": "A?!?", "rule": "syntax",
     "note": "`!?` carries its own `?`"},
    {"naxp": "[]", "rule": "syntax",
     "note": "a character set must contain at least one character"},
    {"naxp": "\\d", "rule": "syntax",
     "note": "undefined escape letter"},
    {"naxp": "\\w", "rule": "syntax",
     "note": "undefined escape letter"},
    {"naxp": "\\Z", "rule": "syntax",
     "note": "undefined escape letter"},
    {"naxp": "A*", "rule": "syntax",
     "note": "`*` is reserved: naxp has no unbounded repetition"},
    {"naxp": "A+", "rule": "syntax",
     "note": "`+` is reserved, for the same reason"},
    {"naxp": ".", "rule": "syntax",
     "note": "`.` is reserved: write the character set meant"},
    {"naxp": "^A", "rule": "syntax",
     "note": "`^` is reserved: a naxp matches the whole text, so there are no anchors"},
    {"naxp": "A$", "rule": "syntax",
     "note": "`$` is reserved, for the same reason"},
    {"naxp": "A{0}", "rule": "W4",
     "note": "a fixed count of zero matches only the empty string, which is written `()`"},
    {"naxp": "A{0,0}", "rule": "W4",
     "note": "the same, written as an interval"},
    {"naxp": "\\ s", "rule": "syntax",
     "note": "whitespace may not split an escape"},
    {"naxp": "A! !", "rule": "syntax",
     "note": "`!!` is one token"},
    {"naxp": "A{2 5}", "rule": "syntax",
     "note": "whitespace may not split a run of digits"},
    {"naxp": "# [0-10]", "rule": "syntax",
     "note": "`#[` is one token"},
    {"naxp": "#[1 0-20]", "rule": "syntax",
     "note": "whitespace may not split a run of digits"},
    {"naxp": "A{2,}", "rule": "syntax",
     "note": "there is no unbounded interval"},
    {"naxp": "A{2-5}", "rule": "syntax",
     "note": "the interval separator is `-`, not a comma"},
    {"naxp": "(A", "rule": "syntax",
     "note": "unclosed group"},
    {"naxp": "[A-E", "rule": "syntax",
     "note": "unclosed character set"},
    {"naxp": "[E-A]", "rule": "W4",
     "note": "a range must be written lowest first; the bounds of every range and count are W4's"},
    {"naxp": "!", "rule": "syntax",
     "note": "a bare reserved character"},
    {"naxp": "A|", "rule": "syntax",
     "note": "an alternative must contain at least one element"},
    {"naxp": "\\s!(B|C)", "rule": "W1",
     "note": "the rendering generates two strings"},
    {"naxp": "\\s!\\-", "rule": "W1",
     "note": "the subject never accepts a hyphen"},
    {"naxp": "\\s!()", "rule": "W1",
     "note": "`\\s` does not generate the empty string"},
    {"naxp": "\\A!!", "rule": "W1",
     "note": "the subject of a `!!` must generate exactly one string"},
    {"naxp": "[AB]!!", "rule": "W1",
     "note": "the subject of a `!!` must generate exactly one string"},
    {"naxp": "(B|C)!!", "rule": "W1",
     "note": "the subject of a `!!` must generate exactly one string"},
    {"naxp": "(\\s!?)!?", "rule": "W2",
     "note": "`!` in the subject"},
    {"naxp": "(A|B)!(B!B)", "rule": "W2",
     "note": "`!` hidden in the rendering"},
    {"naxp": "AB!!B?C", "rule": "W3",
     "note": "ABC has two canonical forms, ABC and ABBC"},
    {"naxp": "#[0!-9]", "rule": "W4",
     "note": "the units digit is the number, not padding in front of it"},
    {"naxp": "#[10?5-999]", "rule": "W4",
     "note": "a zero inside the number, which is not a padding position"},
    {"naxp": "#[1!05-999]", "rule": "W4",
     "note": "only a zero may be marked"},
    {"naxp": "#[0-9!]", "rule": "W4",
     "note": "only the lower bound may carry padding marks"},
    {"naxp": "#[0 !0-9]", "rule": "syntax",
     "note": "a padding mark belongs to the zero before it"},
    {"naxp": "#[0! 0-9]", "rule": "syntax",
     "note": "whitespace may not split a run of digits"},
    {"naxp": "(#[0!0-105])!(07)", "rule": "W2",
     "note": "a marked range holds a `!` once expanded, so it may not sit inside one"},
    {"naxp": "#[0!0!0-105]\\9?", "rule": "W3",
     "note": "an optional digit after a marked range: 00 is the value 0 padded once, or padded none with a zero after it"},
    {"naxp": "#[10-5]", "rule": "W4",
     "note": "lo has more digits than hi"},
    {"naxp": "#[00-5]", "rule": "W4",
     "note": "lo has more digits than hi"},
    {"naxp": "#[0-05]", "rule": "W4",
     "note": "hi has a leading zero while wider than lo"},
    {"naxp": "#[0000000000000000-1]", "rule": "W4",
     "note": "a bound of sixteen digits"},
    {"naxp": "#[0-9999999999999999]", "rule": "W4",
     "note": "a bound of sixteen digits"},
    {"naxp": "A{12345}", "rule": "W4",
     "note": "an interval count of five digits, where two is the most allowed"},
    {"naxp": "A{123}", "rule": "W4",
     "note": "an interval count of three digits, one more than allowed"},
    {"naxp": "A{5,2}", "rule": "W4",
     "note": "the first count exceeds the second"},
    {"naxp": "\\9{20}", "rule": "W5",
     "note": "10^20 values, above 2^64 - 1"},
    {"naxp": "\\C", "rule": "syntax",
     "note": "a case fold must be followed by the expression it binds to"},
    {"naxp": "A!\\CA", "rule": "syntax",
     "note": "a case fold cannot begin a rendering; a rendering is one string, written in the case wanted"},
    {"naxp": "[\\CA]", "rule": "syntax",
     "note": "a fold applies to a whole element, so it is not an item of a character set"},
    {"naxp": "(\\CA)!A", "rule": "W2",
     "note": "a fold is a `!` once expanded, so this one is inside the subject of a `!`"},
    {"naxp": "A!(\\CA)", "rule": "W2",
     "note": "the same, in the rendering"},
    {"naxp": "\\C(A!?|a)", "rule": "W3",
     "note": "`A!?|a` is well formed; folding it lets `a` match both branches, giving it two canonical forms"},
    {"naxp": "(A{50}){40}", "rule": "W6",
     "note": "2000 positions, so 2001 states, one past what W6 allows"},
    {"naxp": "(A{99}){99}", "rule": "W6",
     "note": "the specification's own example: eleven characters of pattern, a single string of 9801 characters, and one encoded value"},
]
