// Copyright (c) Tim Gordon.
// This file is licensed to you under the Apache Licence, Version 2.0. See the LICENSE file.

/**
 * Writes the library as one naxp.cpp with naxp.h and naxp.hpp beside it, in the manner of
 * sqlite3.c. That is what the R package vendors, what a Python wheel or a Rust crate builds
 * from, and what a release attaches, because none of them wants a CMake project.
 *
 *     node src/cpp/tools/amalgamate.js [--out DIR]
 *
 * The source list and the version come from CMakeLists.txt, so that both stay stated once.
 * naxp.cpp is every source in that list with each #include "..." replaced by the file it names,
 * once, include guards intact; the two public headers are inlined too, so that naxp.cpp
 * compiles with no include path at all. NAXP_VERSION, which the CMake build defines on the
 * command line, is defined at the top. naxp.h and naxp.hpp are copied unchanged.
 *
 * The output is generated, never edited, and not committed. Lines end in LF whatever the
 * working copy holds, so that the same tree gives the same bytes on every platform.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// The command line

const options = { out: join(root, 'build', 'amalgamation') };

for (let i = 2; i < process.argv.length; i += 2) {
	const name = process.argv[i].replace(/^--/, '');
	const value = process.argv[i + 1];

	if (!(name in options) || value === undefined) {
		console.error('Usage: node amalgamate.js [--out DIR]');
		process.exit(2);
	}

	options[name] = value;
}

// What CMakeLists.txt states

const cmake = read(join(root, 'CMakeLists.txt'));

const version = cmake.match(/^\s*VERSION\s+(\d+\.\d+\.\d+)\s*$/m)?.[1];
const sources = cmake.match(/add_library\(naxp STATIC([^)]*)\)/)?.[1].split(/\s+/).filter((name) => name.endsWith('.cpp'));

if (version === undefined || !sources?.length) {
	console.error('CMakeLists.txt does not state the version and the sources in the shape this script reads.');
	process.exit(1);
}

// The expansion

const banner = [
	'// Copyright (c) Tim Gordon.',
	'// This file is licensed to you under the Apache Licence, Version 2.0. See the LICENSE file.',
];

const inlined = new Set();
const output = [
	...banner,
	'',
	`// naxp ${version}: the whole library in one file, generated by tools/amalgamate.js from the`,
	'// sources it names below. Edit those, not this. The public headers naxp.h and naxp.hpp are',
	'// inlined, so nothing but the standard library is needed to compile it.',
	'',
	`#define NAXP_VERSION "${version}"`,
];

for (const source of sources) {
	inline(join(root, source));
}

/** Appends a file to the output with every local include it names inlined in its place. */
function inline(file) {
	if (inlined.has(file)) {
		return;
	}

	inlined.add(file);

	const name = relative(root, file).replaceAll('\\', '/');
	const lines = read(file).split('\n');

	// Every file opens with the two-line licence banner, which the amalgamation states once.
	if (lines[0].startsWith('// Copyright') || lines[0].startsWith('/* Copyright')) {
		lines.splice(0, lines[1].trim() === '' ? 2 : 3);
	}

	emit('');
	emit(`/* Begin file ${name} */`);

	for (const line of lines) {
		const include = line.match(/^\s*#\s*include\s+"([^"]+)"/);

		if (include === null) {
			emit(line);
		} else {
			inline(locate(include[1], file));
		}
	}

	if (output[output.length - 1] === '') {
		output.pop();
	}

	emit(`/* End file ${name} */`);
}

/** Appends a line, collapsing the blank lines that removing an include leaves behind. */
function emit(line) {
	if (line.trim() !== '' || output[output.length - 1] !== '') {
		output.push(line);
	}
}

/** Finds a quoted include as the compiler would: beside the including file, then on the paths. */
function locate(name, from) {
	for (const directory of [dirname(from), join(root, 'src'), join(root, 'include')]) {
		const candidate = join(directory, name);

		if (existsSync(candidate)) {
			return candidate;
		}
	}

	throw new Error(`${relative(root, from)} includes "${name}", which is not in the tree.`);
}

function read(file) {
	return readFileSync(file, 'utf8').replaceAll('\r\n', '\n');
}

// The output

mkdirSync(options.out, { recursive: true });

writeFileSync(join(options.out, 'naxp.cpp'), output.join('\n') + '\n');
writeFileSync(join(options.out, 'naxp.h'), read(join(root, 'include', 'naxp', 'naxp.h')));
writeFileSync(join(options.out, 'naxp.hpp'), read(join(root, 'include', 'naxp', 'naxp.hpp')));

console.log(`Wrote naxp ${version} as naxp.cpp, naxp.h and naxp.hpp to ${options.out}`);
